# Release snapshot packages to NPM.

name: Release Snapshots

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-snapshots:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i

      - name: Add snapshot changeset
        run: |
          cat << EOF > ".changeset/snap-release-changeset.md"
            ---
            "test-changesets-action": patch
            ---
            Add snapshot changeset for snapshot releases
          EOF

      - name: Version packages as "package@0.0.0-snap-{timestamp}"
        run: npx changeset version --snapshot snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check status of the published outputs
        run: | 
          echo "published=${{ steps.changesets.outputs.published }}"
          echo "publishedPackages=${{ steps.changesets.outputs.publishedPackages }}"

      - name: Publish to npm (ignore GitHub)
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm changeset publish --no-git-tag --tag snap
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Create commit comment
                uses: peter-evans/commit-comment@v3
                if: ${{ steps.changesets.outputs.published == 'true' }}
                with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  body: |
                    ```json
                    ${{ steps.changesets.outputs.publishedPackages }}
                    ```
